
  CREATE TABLE "PAX"."FATO_SUMLOG"
   (	"DATA" DATE,
	"BWL_CURRENT" NUMBER(38,0),
	"BRT_AVERAGE" NUMBER,
	"BPF_AVERAGE" NUMBER,
	"METRICA_LINK_ID" NUMBER NOT NULL ENABLE,
	"METRICA_ID" NUMBER NOT NULL ENABLE,
	"HOST_ID" NUMBER NOT NULL ENABLE,
	"SISTEMA_ID" NUMBER,
	"METRICA_LINK_ID_PARENT" NUMBER,
	"METRICA_LINK_ID_PARTNER" NUMBER,
	"TYPE" CHAR(8),
	"BPF_GOOD" NUMBER,
	"BPF_WARNING" NUMBER,
	"BPF_CRITICAL" NUMBER,
	"BRT_GOOD" NUMBER,
	"BRT_WARNING" NUMBER,
	"BRT_CRITICAL" NUMBER,
	"BWL_GOOD" NUMBER,
	"BWL_WARNING" NUMBER,
	"BWL_CRITICAL" NUMBER,
	"BPF_TIME_UNIT" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

