
  CREATE TABLE "PAX"."FATO_SUMLOG1"
   (	"DATA" DATE,
	"BWL_CURRENT" NUMBER(38,0),
	"BRT_AVERAGE" NUMBER,
	"BPF_AVERAGE" NUMBER,
	"METRICA_LINK_ID" NUMBER NOT NULL ENABLE,
	"METRICA_ID" NUMBER NOT NULL ENABLE,
	"HOST_ID" NUMBER NOT NULL ENABLE,
	"SISTEMA_ID" NUMBER,
	"METRICA_LINK_ID_PARENT" NUMBER,
	"METRICA_LINK_ID_PARTNER" NUMBER,
	"TYPE" CHAR(8)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

