
  CREATE TABLE "PAX"."FATO_COLETA"
   (	"DATA" DATE NOT NULL ENABLE,
	"HOST_ID" NUMBER NOT NULL ENABLE,
	"CLIENTE_ID" NUMBER,
	"SITE_ID" NUMBER,
	"ORIGEM" VARCHAR2(30) NOT NULL ENABLE,
	"AMBIENTE_ID" NUMBER,
	"SISTEMA_ID" NUMBER,
	"PRODUTO_ID" NUMBER,
	"METRICA_ID" NUMBER NOT NULL ENABLE,
	"CF" VARCHAR2(30) NOT NULL ENABLE,
	"VALOR" FLOAT(38) NOT NULL ENABLE,
	"METRICA_LINK_ID" NUMBER(10,0) NOT NULL ENABLE,
	"BPF_GOOD" NUMBER(38,0),
	"BPF_WARNING" NUMBER(38,0),
	"BPF_CRITICAL" NUMBER(38,0),
	"BRT_GOOD" NUMBER(38,0),
	"BRT_WARNING" NUMBER(38,0),
	"BRT_CRITICAL" NUMBER(38,0),
	"BWL_GOOD" NUMBER(38,0),
	"BWL_WARNING" NUMBER(38,0),
	"BWL_CRITICAL" NUMBER(38,0),
	"BWL_CURRENT" NUMBER(38,0),
	"BPF_TIME_UNIT" NUMBER(38,0),
	"BPF_ROI" NUMBER,
	"BRT_ROI" NUMBER,
	"BWL_ROI" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1066401792 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

