
  CREATE TABLE "PAX"."MV_DIM_TEMPO"
   (	"DATA" DATE NOT NULL ENABLE,
	"PERIODO" VARCHAR2(9),
	"ANO_CODE" VARCHAR2(4),
	"ANO" VARCHAR2(4),
	"TRIMESTRE_CODE" VARCHAR2(5),
	"TRIMESTRE" VARCHAR2(1),
	"MES_CODE" VARCHAR2(6),
	"MES_NUM" VARCHAR2(2),
	"MES" VARCHAR2(3),
	"SEMANA_ANO" VARCHAR2(2),
	"SEMANA_MES" VARCHAR2(1),
	"DIA_SEMANA" VARCHAR2(3),
	"DIA_CODE" VARCHAR2(8),
	"DIA" VARCHAR2(2),
	"DIA_UTIL" VARCHAR2(1),
	"HORA" VARCHAR2(2),
	"HORA_CODE" VARCHAR2(10),
	"MINUTO" VARCHAR2(2),
	"SEGUNDO" VARCHAR2(2)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"

