
  CREATE TABLE "PAX"."MV_DIM_HOST"
   (	"HOST_ID" NUMBER NOT NULL ENABLE,
	"HOSTNAME" VARCHAR2(100) NOT NULL ENABLE,
	"TIPO_CPU" VARCHAR2(100),
	"NUM_CPU" NUMBER,
	"QTD_MEMORIA" NUMBER
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"

