
  CREATE TABLE "PAX"."PMA_DADO_BRUTO"
   (	"DATA_INSERCAO" VARCHAR2(30),
	"CHAMADO" VARCHAR2(50),
	"TITULO" VARCHAR2(4000),
	"DATA_CRIACAO" VARCHAR2(30),
	"STATUS" VARCHAR2(100),
	"TIPO_CHAMADO" VARCHAR2(100),
	"SOLICITANTE" VARCHAR2(100),
	"SEGUNDOS" NUMBER(20,0),
	"PROJETO" VARCHAR2(100),
	"HOST" VARCHAR2(4000),
	"RESPONSAVEL" VARCHAR2(100),
	"PRIORIDADE" VARCHAR2(100),
	"CRIADOR" VARCHAR2(100),
	"RESOLUCAO" VARCHAR2(100),
	"DATA_FECHAMENTO" VARCHAR2(30),
	"DATA_ATUALIZACAO" VARCHAR2(30),
	"TIPO_RELACAO" VARCHAR2(100),
	"RELACAO" VARCHAR2(100),
	"RELACIONADAS" VARCHAR2(4000),
	"DATA_INICIO_PARADA" VARCHAR2(30),
	"DATA_FIM_PARADA" VARCHAR2(30),
	"TIPO_PARADA" VARCHAR2(500)
   )
   ORGANIZATION EXTERNAL
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "PMA_EXTERNAL_DIR"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY newline CHARACTERSET AL32UTF8 FIELDS TERMINATED BY
';' missing field values are null  REJECT ROWS WITH ALL NULL FIELDS
	      )
      LOCATION
       ( "PMA_EXTERNAL_DIR":'pma.txt'
       )
    )

