
  CREATE TABLE "PAX"."PMP_LOCAL_PATCHES"
   (	"LOCAL_PATCHES_ID" NUMBER NOT NULL ENABLE,
	"FABRICANTE_ID" NUMBER,
	"URL" VARCHAR2(4000),
	"DESCRICAO" VARCHAR2(4000),
	 CONSTRAINT "PMP_LOCAL_PATCHES_PK" PRIMARY KEY ("LOCAL_PATCHES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"  ENABLE,
	 CONSTRAINT "PMP_LOCAL_PATCHES_PMP_FAB_FK1" FOREIGN KEY ("FABRICANTE_ID")
	  REFERENCES "PAX"."PMP_FABRICANTE" ("FABRICANTE_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"

