
  CREATE TABLE "PAX"."PMP_INSTANCIA_TIPO_CHECKLIST"
   (	"INSTANCIA_TIPO_CHECKLIST_ID" NUMBER NOT NULL ENABLE,
	"INSTANCIA_ID" NUMBER NOT NULL ENABLE,
	"TIPO_CHECKLIST_ID" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "PMP_INSTANCIA_TIPO_CHECKL_PK" PRIMARY KEY ("INSTANCIA_TIPO_CHECKLI
ST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"  ENABLE,
	 CONSTRAINT "PMP_INSTANCIA_TIPO_CHECKL_UK1" UNIQUE ("INSTANCIA_ID", "TIPO_CHECK
LIST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"  ENABLE,
	 CONSTRAINT "PMP_INSTANCIA_TIPO_CHECKL_FK1" FOREIGN KEY ("INSTANCIA_ID")
	  REFERENCES "PAX"."PMP_INSTANCIA" ("INSTANCIA_ID") ENABLE,
	 CONSTRAINT "PMP_INSTANCIA_TIPO_CHECKL_FK2" FOREIGN KEY ("TIPO_CHECKLIST_ID")
	  REFERENCES "PAX"."PMP_TIPO_CHECKLIST" ("TIPO_CHECKLIST_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"

