
  CREATE TABLE "PAX"."PMP_GRAFICO"
   (	"GRAFICO_ID" NUMBER NOT NULL ENABLE,
	"INSTANCIA_ID" NUMBER,
	"TITULO" VARCHAR2(100),
	"GRAFICO_CONTROLE_ID" NUMBER,
	"MES_ANO" NUMBER,
	"TIPO_CALCULO_ID" NUMBER,
	"DESCRICAO" VARCHAR2(2048),
	"TIPO_GRAFICO_ID" NUMBER,
	"CAPITULO" NUMBER,
	 CONSTRAINT "PMP_GRAFICO_PK" PRIMARY KEY ("GRAFICO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"  ENABLE,
	 CONSTRAINT "PMP_GRAFICO_PMP_TIPO_CALC_FK1" FOREIGN KEY ("TIPO_CALCULO_ID")
	  REFERENCES "PAX"."PMP_TIPO_CALCULO" ("TIPO_CALCULO_ID") ENABLE,
	 CONSTRAINT "PMP_GRAFICO_PMP_INSTANCIA_FK1" FOREIGN KEY ("INSTANCIA_ID")
	  REFERENCES "PAX"."PMP_INSTANCIA" ("INSTANCIA_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"

