
  CREATE TABLE "PAX"."PMP_TASK_RELACAO"
   (	"TASK_RELACAO_ID" NUMBER,
	"TASK_ID" NUMBER NOT NULL ENABLE,
	"TASK_RELACIONADA_ID" NUMBER NOT NULL ENABLE,
	"RELACAO_ID" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "PMP_TASK_RELACAO_PK" PRIMARY KEY ("TASK_ID", "TASK_RELACIONADA_ID"
, "RELACAO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"  ENABLE,
	 CONSTRAINT "PMP_TASK_RELACAO_UK1" UNIQUE ("TASK_RELACAO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"  ENABLE,
	 CONSTRAINT "PMP_TASK_RELACAO_PMP_RELA_FK1" FOREIGN KEY ("RELACAO_ID")
	  REFERENCES "PAX"."PMP_RELACAO" ("RELACAO_ID") ENABLE,
	 CONSTRAINT "PMP_TASK_RELACAO_PMP_TASK_FK2" FOREIGN KEY ("TASK_RELACIONADA_ID")

	  REFERENCES "PAX"."PMP_TASK" ("TASK_ID") ON DELETE CASCADE ENABLE,
	 CONSTRAINT "PMP_TASK_RELACAO_PMP_TASK_FK1" FOREIGN KEY ("TASK_ID")
	  REFERENCES "PAX"."PMP_TASK" ("TASK_ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"

