
  CREATE TABLE "PAX"."PMP_TASK_BKP20141010"
   (	"TASK_ID" NUMBER NOT NULL ENABLE,
	"DATA_INSERCAO" DATE NOT NULL ENABLE,
	"CHAMADO" VARCHAR2(30) NOT NULL ENABLE,
	"TITULO" VARCHAR2(4000),
	"DATA_CRIACAO" DATE,
	"STATUS" VARCHAR2(30),
	"TIPO_CHAMADO" VARCHAR2(30),
	"SOLICITANTE" VARCHAR2(50),
	"SEGUNDOS_TRABALHADOS" NUMBER(20,0),
	"RESPONSAVEL" VARCHAR2(30),
	"PRIORIDADE" VARCHAR2(30),
	"CRIADOR" VARCHAR2(30),
	"RESOLUCAO" VARCHAR2(100),
	"DATA_FECHAMENTO" DATE,
	"DATA_ATUALIZACAO" DATE,
	"CLIENTE_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"

