
  CREATE TABLE "PAX"."PMP_ALERT"
   (	"ALERT_ID" NUMBER NOT NULL ENABLE,
	"CHECKLIST_ID" NUMBER NOT NULL ENABLE,
	"ORA_ID" NUMBER NOT NULL ENABLE,
	"QUANTIDADE" NUMBER DEFAULT 1 NOT NULL ENABLE,
	"CHECAGEM" NUMBER(1,0),
	 CONSTRAINT "PMP_ALERT_PK" PRIMARY KEY ("ALERT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"  ENABLE,
	 CONSTRAINT "PMP_ALERT_PMP_CHECKLIST_FK1" FOREIGN KEY ("CHECKLIST_ID")
	  REFERENCES "PAX"."PMP_CHECKLIST" ("CHECKLIST_ID") ENABLE,
	 CONSTRAINT "PMP_ALERT_PMP_ORA_FK1" FOREIGN KEY ("ORA_ID")
	  REFERENCES "PAX"."PMP_ORA" ("ORA_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"

