
  CREATE TABLE "PAX"."PMP_PATCH_PRODUTO"
   (	"PATCH_PRODUTO_ID" NUMBER NOT NULL ENABLE,
	"PATCH_ID" NUMBER,
	"PRODUTO_DEP_ID" NUMBER,
	 CONSTRAINT "PMP_PATCH_PRODUTO_PK" PRIMARY KEY ("PATCH_PRODUTO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"  ENABLE,
	 CONSTRAINT "PMP_PATCH_PRODUTO_PMP_PAT_FK1" FOREIGN KEY ("PATCH_ID")
	  REFERENCES "PAX"."PMP_PATCH" ("PATCH_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"

