
  CREATE TABLE "PAX"."PMP_PRODUTO"
   (	"PRODUTO_ID" NUMBER,
	"PRODUTO" VARCHAR2(500),
	"VERSAO" VARCHAR2(40),
	"DESCRICAO" VARCHAR2(4000),
	"FABRICANTE_ID" NUMBER,
	"BITS" NUMBER,
	 CONSTRAINT "PMP_PRODUTO_PK" PRIMARY KEY ("PRODUTO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE,
	 CONSTRAINT "PMP_PRODUTO_PMP_FABRICANT_FK1" FOREIGN KEY ("FABRICANTE_ID")
	  REFERENCES "PAX"."PMP_FABRICANTE" ("FABRICANTE_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

