
  CREATE TABLE "PAX"."PMP_BUK"
   (	"METRICA_LINK_ID" NUMBER NOT NULL ENABLE,
	"SISTEMA_ID" NUMBER NOT NULL ENABLE,
	"BPF_GOOD" NUMBER,
	"BPF_WARNING" NUMBER,
	"BPF_CRITICAL" NUMBER,
	"BWL_GOOD" NUMBER,
	"BWL_WARNING" NUMBER,
	"BWL_CRITICAL" NUMBER,
	"BRT_GOOD" NUMBER,
	"BRT_WARNING" NUMBER,
	"BRT_CRITICAL" NUMBER,
	"BPF_TIME_UNIT" NUMBER,
	"METRICA_LINK_ID_PARENT" NUMBER,
	"METRICA_LINK_ID_PARTNER" NUMBER,
	"ENABLED" VARCHAR2(1) NOT NULL ENABLE,
	"DESCRICAO" VARCHAR2(1000),
	"BWL_CURRENT" NUMBER(38,0),
	"HOST_ID" NUMBER NOT NULL ENABLE,
	"BPF_ROI" NUMBER,
	"BRT_ROI" NUMBER,
	"BWL_ROI" NUMBER,
	"BUK_ID" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "PMP_BUK_PK" PRIMARY KEY ("BUK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE,
	 CONSTRAINT "PMP_BUK_PMP_HOST_FK1" FOREIGN KEY ("HOST_ID")
	  REFERENCES "PAX"."PMP_HOST" ("HOST_ID") ENABLE,
	 CONSTRAINT "PMP_BUK_PMP_METRICA_LINK_FK1" FOREIGN KEY ("METRICA_LINK_ID")
	  REFERENCES "PAX"."PMP_METRICA_LINK" ("METRICA_LINK_ID") DISABLE,
	 CONSTRAINT "PMP_BUK_PMP_SISTEMA_FK1" FOREIGN KEY ("SISTEMA_ID")
	  REFERENCES "PAX"."PMP_SISTEMA" ("SISTEMA_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

