
  CREATE TABLE "PAX"."PMP_GRAFICO_BKP"
   (	"GRAFICO_ID" NUMBER NOT NULL ENABLE,
	"INSTANCIA_ID" NUMBER,
	"TITULO" VARCHAR2(100),
	"GRAFICO_CONTROLE_ID" NUMBER,
	"MES_ANO" NUMBER,
	"TIPO_CALCULO_ID" NUMBER,
	"DESCRICAO" VARCHAR2(2048)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"

