
  CREATE TABLE "PAX"."PMP_PATCHES_HOST_AMBIENTE"
   (	"PATCHES_HOST_AMBIENTE_ID" NUMBER NOT NULL ENABLE,
	"HOST_AMBIENTE_ID" NUMBER NOT NULL ENABLE,
	"PATCH_ID" NUMBER NOT NULL ENABLE,
	"DATA_IMPLANTACAO" DATE,
	"STATUS_ID" NUMBER,
	 CONSTRAINT "PMP_PATCHES_HOST_AMBIENTE_PK" PRIMARY KEY ("PATCHES_HOST_AMBIENTE_
ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"  ENABLE,
	 CONSTRAINT "PMP_PATCHES_HOST_AMBIENTE_FK1" FOREIGN KEY ("HOST_AMBIENTE_ID")
	  REFERENCES "PAX"."PMP_HOST_AMBIENTE" ("HOST_AMBIENTE_ID") ENABLE,
	 CONSTRAINT "PMP_PATCHES_HOST_AMBIENTE_FK2" FOREIGN KEY ("PATCH_ID")
	  REFERENCES "PAX"."PMP_PATCH" ("PATCH_ID") ENABLE,
	 CONSTRAINT "PMP_PATCHES_HOST_AMBIENTE_FK3" FOREIGN KEY ("STATUS_ID")
	  REFERENCES "PAX"."PMP_STATUS" ("STATUS_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"

