
  CREATE TABLE "PAX"."PMP_PATCH"
   (	"PATCH_ID" NUMBER NOT NULL ENABLE,
	"PRODUTO_ID" NUMBER NOT NULL ENABLE,
	"CONSEQUENCIAS" VARCHAR2(4000),
	"CRITICIDADE_ID" NUMBER,
	"DATA_DISPONIBILIDADE" DATE,
	"DATA_CADASTRO" DATE,
	"DESCRICAO" VARCHAR2(4000),
	"PATCH" VARCHAR2(20),
	"TIPO_ID" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "PMP_PATCH_PK" PRIMARY KEY ("PATCH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"  ENABLE,
	 CONSTRAINT "PMP_PATCH_PMP_CRITICIDADE_FK1" FOREIGN KEY ("CRITICIDADE_ID")
	  REFERENCES "PAX"."PMP_CRITICIDADE" ("CRITICIDADE_ID") ENABLE,
	 CONSTRAINT "PMP_PATCH_PMP_TIPO_FK1" FOREIGN KEY ("TIPO_ID")
	  REFERENCES "PAX"."PMP_TIPO" ("TIPO_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"

