
  CREATE TABLE "PAX"."PMP_CHECKLIST"
   (	"CHECKLIST_ID" NUMBER NOT NULL ENABLE,
	"DATA" DATE NOT NULL ENABLE,
	"INSTANCIA_ID" NUMBER NOT NULL ENABLE,
	"COMENTARIOS" VARCHAR2(500),
	"CONCLUSAO_CHECKLIST" NUMBER(1,0) NOT NULL ENABLE,
	 CONSTRAINT "PMP_CHECKLIST_PK" PRIMARY KEY ("DATA", "INSTANCIA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"  ENABLE,
	 CONSTRAINT "PMP_CHECKLIST_UK1" UNIQUE ("CHECKLIST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"  ENABLE,
	 CONSTRAINT "PMP_CHECKLIST_PMP_INSTANC_FK1" FOREIGN KEY ("INSTANCIA_ID")
	  REFERENCES "PAX"."PMP_INSTANCIA" ("INSTANCIA_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"

