
  CREATE TABLE "PAX"."PMP_TIME_FRAME_BKP"
   (	"TIME_FRAME_ID" NUMBER NOT NULL ENABLE,
	"GRAFICO_ID" NUMBER NOT NULL ENABLE,
	"METRICA_LINK_ID" NUMBER NOT NULL ENABLE,
	"LEGENDA" VARCHAR2(1000) NOT NULL ENABLE,
	"TIPO_HORARIO_ID" NUMBER NOT NULL ENABLE,
	"TIME_FRAME_CONTROLE_ID" NUMBER NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"

