
  CREATE TABLE "PAX"."PMP_HOST"
   (	"HOST_ID" NUMBER NOT NULL ENABLE,
	"HOSTNAME" VARCHAR2(100) NOT NULL ENABLE,
	"TIPO_CPU" VARCHAR2(100),
	"NUM_CPU" NUMBER,
	"QTD_MEMORIA" NUMBER,
	"DESCRICAO" VARCHAR2(4000),
	"CLIENTE_ID" NUMBER,
	"SITE_ID" NUMBER,
	"NOME_FANTASIA" VARCHAR2(30),
	"IP" VARCHAR2(50),
	"USUARIO" VARCHAR2(50),
	"SENHA" VARCHAR2(50),
	 CONSTRAINT "PMP_HOST_PK" PRIMARY KEY ("HOST_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE,
	 CONSTRAINT "PMP_HOST_CLIENTE_ID_FK" FOREIGN KEY ("CLIENTE_ID")
	  REFERENCES "PAX"."PMP_CLIENTE" ("CLIENTE_ID") ENABLE,
	 CONSTRAINT "PMP_HOST_SITE_ID_FK" FOREIGN KEY ("SITE_ID")
	  REFERENCES "PAX"."PMP_SITE" ("SITE_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"

