
  CREATE TABLE "PAX"."ZB_METRICA_LINK"
   (	"METRICA_LINK_ID" NUMBER NOT NULL ENABLE,
	"HOST_AMBIENTE_ID" NUMBER NOT NULL ENABLE,
	"METRICA_ID" NUMBER NOT NULL ENABLE,
	"DESCRICAO" VARCHAR2(4000),
	 CONSTRAINT "ZB_METRICA_LINK_PK" PRIMARY KEY ("METRICA_LINK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE,
	 CONSTRAINT "ZB_METRICA_LINK_PMP_HOST__FK1" FOREIGN KEY ("HOST_AMBIENTE_ID")
	  REFERENCES "PAX"."PMP_HOST_AMBIENTE" ("HOST_AMBIENTE_ID") ENABLE,
	 CONSTRAINT "ZB_METRICA_LINK_ZB_METRIC_FK1" FOREIGN KEY ("METRICA_ID")
	  REFERENCES "PAX"."ZB_METRICA" ("METRICA_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TS_DATA_PAX"

